include("${Datastore_SOURCE_DIR}/cmake/dbms_glob_sources.cmake")
add_headers_and_sources(datastore_dictionaries_embedded .)
add_headers_and_sources(datastore_dictionaries_embedded GeodataProviders)
add_library(datastore_dictionaries_embedded ${datastore_dictionaries_embedded_sources})
target_link_libraries(datastore_dictionaries_embedded PRIVATE datastore_common_io)
if (TARGET ch::mysqlxx)
    target_link_libraries(datastore_dictionaries_embedded PRIVATE ch::mysqlxx)
endif()
