// Generated by Zap compiler, DO NOT EDIT
// source: datastore.zap

#include "datastore.zap.h"

namespace zap {
namespace schemas {
static const ::zap::_::AlignedData<40> b_ee0e33b15763bd12 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     18, 189,  99,  87, 177,  51,  14, 238,
     14,   0,   0,   0,   3,   0,   0,   0,
     80, 194, 240, 188,  14,  99,  42, 217,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   3,   0,   0, 203,   5,   0,   0,
     21,   0,   0,   0, 194,   0,   0,   0,
     29,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     25,   0,   0,   0, 135,   0,   0,   0,
    109,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    100,  97, 116,  97, 115, 116, 111, 114,
    101,  46, 122,  97, 112,  58,  68,  97,
    116,  97, 115, 116, 111, 114, 101,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      8,   0,   0,   0,   3,   0,   5,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     63, 151,  73,  84, 217, 162, 101, 171,
    243, 235,  31, 227, 221,  34, 145, 249,
     49,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     37,   0,   0,   0,   7,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
     97, 246, 146, 178,  62, 164, 126, 132,
     34, 115, 130, 108,  94,  15, 129, 250,
     25,   0,   0,   0,  82,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     17,   0,   0,   0,   7,   0,   0,   0,
    105, 110, 115, 101, 114, 116,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
    101, 120, 101,  99,  81, 117, 101, 114,
    121,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
      0,   0,   0,   0,   1,   0,   1,   0, }
};
::zap::word const* const bp_ee0e33b15763bd12 = b_ee0e33b15763bd12.words;
#if !ZAP_LITE
static const ::zap::_::RawSchema* const d_ee0e33b15763bd12[] = {
  &s_847ea43eb292f661,
  &s_ab65a2d95449973f,
  &s_f99122dde31febf3,
  &s_fa810f5e6c827322,
};
static const uint16_t m_ee0e33b15763bd12[] = {1, 0};
const ::zap::_::RawSchema s_ee0e33b15763bd12 = {
  0xee0e33b15763bd12, b_ee0e33b15763bd12.words, 40, d_ee0e33b15763bd12, m_ee0e33b15763bd12,
  4, 2, nullptr, nullptr, nullptr, { &s_ee0e33b15763bd12, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !ZAP_LITE
static const ::zap::_::AlignedData<80> b_ab65a2d95449973f = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     63, 151,  73,  84, 217, 162, 101, 171,
     24,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    120,   3,   0,   0, 175,   3,   0,   0,
     21,   0,   0,   0,  50,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0, 231,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    100,  97, 116,  97, 115, 116, 111, 114,
    101,  46, 122,  97, 112,  58,  68,  97,
    116,  97, 115, 116, 111, 114, 101,  46,
    105, 110, 115, 101, 114, 116,  36,  80,
     97, 114,  97, 109, 115,   0,   0,   0,
     16,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     97,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     96,   0,   0,   0,   3,   0,   1,   0,
    108,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    105,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    100,   0,   0,   0,   3,   0,   1,   0,
    112,   0,   0,   0,   2,   0,   1,   0,
      2,   0,   0,   0,   2,   0,   0,   0,
      0,   0,   1,   0,   2,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    104,   0,   0,   0,   3,   0,   1,   0,
    116,   0,   0,   0,   2,   0,   1,   0,
      3,   0,   0,   0,   3,   0,   0,   0,
      0,   0,   1,   0,   3,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    113,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    108,   0,   0,   0,   3,   0,   1,   0,
    120,   0,   0,   0,   2,   0,   1,   0,
    100,  97, 116,  97,  98,  97, 115, 101,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    116,  97,  98, 108, 101,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    102, 111, 114, 109,  97, 116,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    114, 111, 119, 115,   0,   0,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::zap::word const* const bp_ab65a2d95449973f = b_ab65a2d95449973f.words;
#if !ZAP_LITE
static const uint16_t m_ab65a2d95449973f[] = {0, 2, 3, 1};
static const uint16_t i_ab65a2d95449973f[] = {0, 1, 2, 3};
const ::zap::_::RawSchema s_ab65a2d95449973f = {
  0xab65a2d95449973f, b_ab65a2d95449973f.words, 80, nullptr, m_ab65a2d95449973f,
  0, 4, i_ab65a2d95449973f, nullptr, nullptr, { &s_ab65a2d95449973f, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !ZAP_LITE
static const ::zap::_::AlignedData<34> b_f99122dde31febf3 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    243, 235,  31, 227, 221,  34, 145, 249,
     24,   0,   0,   0,   1,   0,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    188,   3,   0,   0, 205,   3,   0,   0,
     21,   0,   0,   0,  58,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    100,  97, 116,  97, 115, 116, 111, 114,
    101,  46, 122,  97, 112,  58,  68,  97,
    116,  97, 115, 116, 111, 114, 101,  46,
    105, 110, 115, 101, 114, 116,  36,  82,
    101, 115, 117, 108, 116, 115,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  66,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    119, 114, 105, 116, 116, 101, 110,   0,
      9,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      9,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::zap::word const* const bp_f99122dde31febf3 = b_f99122dde31febf3.words;
#if !ZAP_LITE
static const uint16_t m_f99122dde31febf3[] = {0};
static const uint16_t i_f99122dde31febf3[] = {0};
const ::zap::_::RawSchema s_f99122dde31febf3 = {
  0xf99122dde31febf3, b_f99122dde31febf3.words, 34, nullptr, m_f99122dde31febf3,
  0, 1, i_f99122dde31febf3, nullptr, nullptr, { &s_f99122dde31febf3, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !ZAP_LITE
static const ::zap::_::AlignedData<50> b_847ea43eb292f661 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     97, 246, 146, 178,  62, 164, 126, 132,
     24,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      2,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    194,   4,   0,   0, 219,   4,   0,   0,
     21,   0,   0,   0,  74,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0, 119,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    100,  97, 116,  97, 115, 116, 111, 114,
    101,  46, 122,  97, 112,  58,  68,  97,
    116,  97, 115, 116, 111, 114, 101,  46,
    101, 120, 101,  99,  81, 117, 101, 114,
    121,  36,  80,  97, 114,  97, 109, 115,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     41,   0,   0,   0,  34,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     36,   0,   0,   0,   3,   0,   1,   0,
     48,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     45,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     40,   0,   0,   0,   3,   0,   1,   0,
     52,   0,   0,   0,   2,   0,   1,   0,
    115, 113, 108,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    102, 111, 114, 109,  97, 116,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::zap::word const* const bp_847ea43eb292f661 = b_847ea43eb292f661.words;
#if !ZAP_LITE
static const uint16_t m_847ea43eb292f661[] = {1, 0};
static const uint16_t i_847ea43eb292f661[] = {0, 1};
const ::zap::_::RawSchema s_847ea43eb292f661 = {
  0x847ea43eb292f661, b_847ea43eb292f661.words, 50, nullptr, m_847ea43eb292f661,
  0, 2, i_847ea43eb292f661, nullptr, nullptr, { &s_847ea43eb292f661, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !ZAP_LITE
static const ::zap::_::AlignedData<35> b_fa810f5e6c827322 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     34, 115, 130, 108,  94,  15, 129, 250,
     24,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    235,   4,   0,   0, 249,   4,   0,   0,
     21,   0,   0,   0,  82,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    100,  97, 116,  97, 115, 116, 111, 114,
    101,  46, 122,  97, 112,  58,  68,  97,
    116,  97, 115, 116, 111, 114, 101,  46,
    101, 120, 101,  99,  81, 117, 101, 114,
    121,  36,  82, 101, 115, 117, 108, 116,
    115,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    114, 101, 115, 117, 108, 116,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::zap::word const* const bp_fa810f5e6c827322 = b_fa810f5e6c827322.words;
#if !ZAP_LITE
static const uint16_t m_fa810f5e6c827322[] = {0};
static const uint16_t i_fa810f5e6c827322[] = {0};
const ::zap::_::RawSchema s_fa810f5e6c827322 = {
  0xfa810f5e6c827322, b_fa810f5e6c827322.words, 35, nullptr, m_fa810f5e6c827322,
  0, 1, i_fa810f5e6c827322, nullptr, nullptr, { &s_fa810f5e6c827322, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !ZAP_LITE
}  // namespace schemas
}  // namespace zap

// =======================================================================================

namespace DB {
namespace Zap {

#if !ZAP_LITE
::zap::Request< ::DB::Zap::Datastore::InsertParams,  ::DB::Zap::Datastore::InsertResults>
Datastore::Client::insertRequest(::kj::Maybe< ::zap::MessageSize> sizeHint) {
  return newCall< ::DB::Zap::Datastore::InsertParams,  ::DB::Zap::Datastore::InsertResults>(
      0xee0e33b15763bd12ull, 0, sizeHint, {true});
}
::kj::Promise<void> Datastore::Server::insert(InsertContext) {
  return ::zap::Capability::Server::internalUnimplemented(
      "datastore.zap:Datastore", "insert",
      0xee0e33b15763bd12ull, 0);
}
::zap::Request< ::DB::Zap::Datastore::ExecQueryParams,  ::DB::Zap::Datastore::ExecQueryResults>
Datastore::Client::execQueryRequest(::kj::Maybe< ::zap::MessageSize> sizeHint) {
  return newCall< ::DB::Zap::Datastore::ExecQueryParams,  ::DB::Zap::Datastore::ExecQueryResults>(
      0xee0e33b15763bd12ull, 1, sizeHint, {true});
}
::kj::Promise<void> Datastore::Server::execQuery(ExecQueryContext) {
  return ::zap::Capability::Server::internalUnimplemented(
      "datastore.zap:Datastore", "execQuery",
      0xee0e33b15763bd12ull, 1);
}
::zap::Capability::Server::DispatchCallResult Datastore::Server::dispatchCall(
    uint64_t interfaceId, uint16_t methodId,
    ::zap::CallContext< ::zap::AnyPointer, ::zap::AnyPointer> context) {
  switch (interfaceId) {
    case 0xee0e33b15763bd12ull:
      return dispatchCallInternal(methodId, context);
    default:
      return internalUnimplemented("datastore.zap:Datastore", interfaceId);
  }
}
::zap::Capability::Server::DispatchCallResult Datastore::Server::dispatchCallInternal(
    uint16_t methodId,
    ::zap::CallContext< ::zap::AnyPointer, ::zap::AnyPointer> context) {
  switch (methodId) {
    case 0:
      return {
        insert(::zap::Capability::Server::internalGetTypedContext<
             ::DB::Zap::Datastore::InsertParams,  ::DB::Zap::Datastore::InsertResults>(context)),
        false,
        false
      };
    case 1:
      return {
        execQuery(::zap::Capability::Server::internalGetTypedContext<
             ::DB::Zap::Datastore::ExecQueryParams,  ::DB::Zap::Datastore::ExecQueryResults>(context)),
        false,
        false
      };
    default:
      (void)context;
      return ::zap::Capability::Server::internalUnimplemented(
          "datastore.zap:Datastore",
          0xee0e33b15763bd12ull, methodId);
  }
}
#endif  // !ZAP_LITE


}  // namespace
}  // namespace
