// Generated by Zap compiler, DO NOT EDIT
// source: datastore.zap

#pragma once

#include <zap/generated-header-support.h>
#include <kj/windows-sanity.h>
#if !ZAP_LITE
#include <zap/capability.h>
#endif  // !ZAP_LITE

#ifndef ZAP_VERSION
#error "ZAP_VERSION is not defined, is zap/generated-header-support.h missing?"
#elif ZAP_VERSION != 2000000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Zap compiler and library."
#endif


ZAP_BEGIN_HEADER

namespace zap {
namespace schemas {

ZAP_DECLARE_SCHEMA(ee0e33b15763bd12);
ZAP_DECLARE_SCHEMA(ab65a2d95449973f);
ZAP_DECLARE_SCHEMA(f99122dde31febf3);
ZAP_DECLARE_SCHEMA(847ea43eb292f661);
ZAP_DECLARE_SCHEMA(fa810f5e6c827322);

}  // namespace schemas
}  // namespace zap

namespace DB {
namespace Zap {

struct Datastore {
  Datastore() = delete;

#if !ZAP_LITE
  class Client;
  class Server;
#endif  // !ZAP_LITE

  struct InsertParams;
  struct InsertResults;
  struct ExecQueryParams;
  struct ExecQueryResults;

  #if !ZAP_LITE
  struct _zapPrivate {
    ZAP_DECLARE_INTERFACE_HEADER(ee0e33b15763bd12)
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
  };
  #endif  // !ZAP_LITE
};

struct Datastore::InsertParams {
  InsertParams() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(ab65a2d95449973f, 0, 4)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct Datastore::InsertResults {
  InsertResults() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(f99122dde31febf3, 1, 0)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct Datastore::ExecQueryParams {
  ExecQueryParams() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(847ea43eb292f661, 0, 2)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

struct Datastore::ExecQueryResults {
  ExecQueryResults() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _zapPrivate {
    ZAP_DECLARE_STRUCT_HEADER(fa810f5e6c827322, 0, 1)
    #if !ZAP_LITE
    static constexpr ::zap::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !ZAP_LITE
  };
};

// =======================================================================================

#if !ZAP_LITE
class Datastore::Client
    : public virtual ::zap::Capability::Client {
public:
  typedef Datastore Calls;
  typedef Datastore Reads;

  Client(decltype(nullptr));
  explicit Client(::kj::Own< ::zap::ClientHook>&& hook);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Server*>()>>
  Client(::kj::Own<_t>&& server);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Server*>()>>
  Client(::kj::Rc<_t>&& server);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Client*>()>>
  Client(::kj::Promise<_t>&& promise);
  Client(::kj::Exception&& exception);
  Client(Client&) = default;
  Client(Client&&) = default;
  Client& operator=(Client& other);
  Client& operator=(Client&& other);

  ::zap::Request< ::DB::Zap::Datastore::InsertParams,  ::DB::Zap::Datastore::InsertResults> insertRequest(
      ::kj::Maybe< ::zap::MessageSize> sizeHint = kj::none);
  ::zap::Request< ::DB::Zap::Datastore::ExecQueryParams,  ::DB::Zap::Datastore::ExecQueryResults> execQueryRequest(
      ::kj::Maybe< ::zap::MessageSize> sizeHint = kj::none);

protected:
  Client() = default;
};

class Datastore::Server
    : public virtual ::zap::Capability::Server {
public:
  typedef Datastore Serves;

  ::zap::Capability::Server::DispatchCallResult dispatchCall(
      uint64_t interfaceId, uint16_t methodId,
      ::zap::CallContext< ::zap::AnyPointer, ::zap::AnyPointer> context)
      override;

protected:
  typedef  ::DB::Zap::Datastore::InsertParams InsertParams;
  typedef  ::DB::Zap::Datastore::InsertResults InsertResults;
  typedef ::zap::CallContext<InsertParams, InsertResults> InsertContext;
  virtual ::kj::Promise<void> insert(InsertContext context);
  typedef  ::DB::Zap::Datastore::ExecQueryParams ExecQueryParams;
  typedef  ::DB::Zap::Datastore::ExecQueryResults ExecQueryResults;
  typedef ::zap::CallContext<ExecQueryParams, ExecQueryResults> ExecQueryContext;
  virtual ::kj::Promise<void> execQuery(ExecQueryContext context);

  inline  ::DB::Zap::Datastore::Client thisCap() {
    return ::zap::Capability::Server::thisCap()
        .template castAs< ::DB::Zap::Datastore>();
  }

  ::zap::Capability::Server::DispatchCallResult dispatchCallInternal(
      uint16_t methodId,
      ::zap::CallContext< ::zap::AnyPointer, ::zap::AnyPointer> context);
};
#endif  // !ZAP_LITE

class Datastore::InsertParams::Reader {
public:
  typedef InsertParams Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline bool hasDatabase() const;
  inline  ::zap::Text::Reader getDatabase() const;

  inline bool hasTable() const;
  inline  ::zap::Text::Reader getTable() const;

  inline bool hasFormat() const;
  inline  ::zap::Text::Reader getFormat() const;

  inline bool hasRows() const;
  inline  ::zap::Data::Reader getRows() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class Datastore::InsertParams::Builder {
public:
  typedef InsertParams Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline bool hasDatabase();
  inline  ::zap::Text::Builder getDatabase();
  inline void setDatabase( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initDatabase(unsigned int size);
  inline void adoptDatabase(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownDatabase();

  inline bool hasTable();
  inline  ::zap::Text::Builder getTable();
  inline void setTable( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initTable(unsigned int size);
  inline void adoptTable(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownTable();

  inline bool hasFormat();
  inline  ::zap::Text::Builder getFormat();
  inline void setFormat( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initFormat(unsigned int size);
  inline void adoptFormat(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownFormat();

  inline bool hasRows();
  inline  ::zap::Data::Builder getRows();
  inline void setRows( ::zap::Data::Reader value);
  inline  ::zap::Data::Builder initRows(unsigned int size);
  inline void adoptRows(::zap::Orphan< ::zap::Data>&& value);
  inline ::zap::Orphan< ::zap::Data> disownRows();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class Datastore::InsertParams::Pipeline {
public:
  typedef InsertParams Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class Datastore::InsertResults::Reader {
public:
  typedef InsertResults Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline  ::uint64_t getWritten() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class Datastore::InsertResults::Builder {
public:
  typedef InsertResults Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline  ::uint64_t getWritten();
  inline void setWritten( ::uint64_t value);

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class Datastore::InsertResults::Pipeline {
public:
  typedef InsertResults Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class Datastore::ExecQueryParams::Reader {
public:
  typedef ExecQueryParams Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline bool hasSql() const;
  inline  ::zap::Text::Reader getSql() const;

  inline bool hasFormat() const;
  inline  ::zap::Text::Reader getFormat() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class Datastore::ExecQueryParams::Builder {
public:
  typedef ExecQueryParams Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline bool hasSql();
  inline  ::zap::Text::Builder getSql();
  inline void setSql( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initSql(unsigned int size);
  inline void adoptSql(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownSql();

  inline bool hasFormat();
  inline  ::zap::Text::Builder getFormat();
  inline void setFormat( ::zap::Text::Reader value);
  inline  ::zap::Text::Builder initFormat(unsigned int size);
  inline void adoptFormat(::zap::Orphan< ::zap::Text>&& value);
  inline ::zap::Orphan< ::zap::Text> disownFormat();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class Datastore::ExecQueryParams::Pipeline {
public:
  typedef ExecQueryParams Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

class Datastore::ExecQueryResults::Reader {
public:
  typedef ExecQueryResults Reads;

  Reader() = default;
  inline explicit Reader(::zap::_::StructReader base): _reader(base) {}

  inline ::zap::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !ZAP_LITE
  inline ::kj::StringTree toString() const {
    return ::zap::_::structString(_reader, *_zapPrivate::brand());
  }
#endif  // !ZAP_LITE

  inline bool hasResult() const;
  inline  ::zap::Data::Reader getResult() const;

private:
  ::zap::_::StructReader _reader;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
  template <typename, ::zap::Kind>
  friend struct ::zap::List;
  friend class ::zap::MessageBuilder;
  friend class ::zap::Orphanage;
};

class Datastore::ExecQueryResults::Builder {
public:
  typedef ExecQueryResults Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::zap::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::zap::MessageSize totalSize() const { return asReader().totalSize(); }
#if !ZAP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !ZAP_LITE

  inline bool hasResult();
  inline  ::zap::Data::Builder getResult();
  inline void setResult( ::zap::Data::Reader value);
  inline  ::zap::Data::Builder initResult(unsigned int size);
  inline void adoptResult(::zap::Orphan< ::zap::Data>&& value);
  inline ::zap::Orphan< ::zap::Data> disownResult();

private:
  ::zap::_::StructBuilder _builder;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
  friend class ::zap::Orphanage;
  template <typename, ::zap::Kind>
  friend struct ::zap::_::PointerHelpers;
};

#if !ZAP_LITE
class Datastore::ExecQueryResults::Pipeline {
public:
  typedef ExecQueryResults Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::zap::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::zap::AnyPointer::Pipeline _typeless;
  friend class ::zap::PipelineHook;
  template <typename, ::zap::Kind>
  friend struct ::zap::ToDynamic_;
};
#endif  // !ZAP_LITE

// =======================================================================================

#if !ZAP_LITE
inline Datastore::Client::Client(decltype(nullptr))
    : ::zap::Capability::Client(nullptr) {}
inline Datastore::Client::Client(
    ::kj::Own< ::zap::ClientHook>&& hook)
    : ::zap::Capability::Client(::kj::mv(hook)) {}
template <typename _t, typename>
inline Datastore::Client::Client(::kj::Own<_t>&& server)
    : ::zap::Capability::Client(::kj::mv(server)) {}
template <typename _t, typename>
inline Datastore::Client::Client(::kj::Rc<_t>&& server)
    : ::zap::Capability::Client(server.toOwn()) {}
template <typename _t, typename>
inline Datastore::Client::Client(::kj::Promise<_t>&& promise)
    : ::zap::Capability::Client(::kj::mv(promise)) {}
inline Datastore::Client::Client(::kj::Exception&& exception)
    : ::zap::Capability::Client(::kj::mv(exception)) {}
inline  ::DB::Zap::Datastore::Client& Datastore::Client::operator=(Client& other) {
  ::zap::Capability::Client::operator=(other);
  return *this;
}
inline  ::DB::Zap::Datastore::Client& Datastore::Client::operator=(Client&& other) {
  ::zap::Capability::Client::operator=(kj::mv(other));
  return *this;
}

#endif  // !ZAP_LITE
inline bool Datastore::InsertParams::Reader::hasDatabase() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Datastore::InsertParams::Builder::hasDatabase() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Datastore::InsertParams::Reader::getDatabase() const {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Datastore::InsertParams::Builder::getDatabase() {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Datastore::InsertParams::Builder::setDatabase( ::zap::Text::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Datastore::InsertParams::Builder::initDatabase(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Datastore::InsertParams::Builder::adoptDatabase(
    ::zap::Orphan< ::zap::Text>&& value) {
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Datastore::InsertParams::Builder::disownDatabase() {
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Datastore::InsertParams::Reader::hasTable() const {
  return !_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline bool Datastore::InsertParams::Builder::hasTable() {
  return !_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Datastore::InsertParams::Reader::getTable() const {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Datastore::InsertParams::Builder::getTable() {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline void Datastore::InsertParams::Builder::setTable( ::zap::Text::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Datastore::InsertParams::Builder::initTable(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), size);
}
inline void Datastore::InsertParams::Builder::adoptTable(
    ::zap::Orphan< ::zap::Text>&& value) {
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Datastore::InsertParams::Builder::disownTable() {
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}

inline bool Datastore::InsertParams::Reader::hasFormat() const {
  return !_reader.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS).isNull();
}
inline bool Datastore::InsertParams::Builder::hasFormat() {
  return !_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Datastore::InsertParams::Reader::getFormat() const {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Datastore::InsertParams::Builder::getFormat() {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS));
}
inline void Datastore::InsertParams::Builder::setFormat( ::zap::Text::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Datastore::InsertParams::Builder::initFormat(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS), size);
}
inline void Datastore::InsertParams::Builder::adoptFormat(
    ::zap::Orphan< ::zap::Text>&& value) {
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Datastore::InsertParams::Builder::disownFormat() {
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<2>() * ::zap::POINTERS));
}

inline bool Datastore::InsertParams::Reader::hasRows() const {
  return !_reader.getPointerField(
      ::zap::bounded<3>() * ::zap::POINTERS).isNull();
}
inline bool Datastore::InsertParams::Builder::hasRows() {
  return !_builder.getPointerField(
      ::zap::bounded<3>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Data::Reader Datastore::InsertParams::Reader::getRows() const {
  return ::zap::_::PointerHelpers< ::zap::Data>::get(_reader.getPointerField(
      ::zap::bounded<3>() * ::zap::POINTERS));
}
inline  ::zap::Data::Builder Datastore::InsertParams::Builder::getRows() {
  return ::zap::_::PointerHelpers< ::zap::Data>::get(_builder.getPointerField(
      ::zap::bounded<3>() * ::zap::POINTERS));
}
inline void Datastore::InsertParams::Builder::setRows( ::zap::Data::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Data>::set(_builder.getPointerField(
      ::zap::bounded<3>() * ::zap::POINTERS), value);
}
inline  ::zap::Data::Builder Datastore::InsertParams::Builder::initRows(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Data>::init(_builder.getPointerField(
      ::zap::bounded<3>() * ::zap::POINTERS), size);
}
inline void Datastore::InsertParams::Builder::adoptRows(
    ::zap::Orphan< ::zap::Data>&& value) {
  ::zap::_::PointerHelpers< ::zap::Data>::adopt(_builder.getPointerField(
      ::zap::bounded<3>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Data> Datastore::InsertParams::Builder::disownRows() {
  return ::zap::_::PointerHelpers< ::zap::Data>::disown(_builder.getPointerField(
      ::zap::bounded<3>() * ::zap::POINTERS));
}

inline  ::uint64_t Datastore::InsertResults::Reader::getWritten() const {
  return _reader.getDataField< ::uint64_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}

inline  ::uint64_t Datastore::InsertResults::Builder::getWritten() {
  return _builder.getDataField< ::uint64_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS);
}
inline void Datastore::InsertResults::Builder::setWritten( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::zap::bounded<0>() * ::zap::ELEMENTS, value);
}

inline bool Datastore::ExecQueryParams::Reader::hasSql() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Datastore::ExecQueryParams::Builder::hasSql() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Datastore::ExecQueryParams::Reader::getSql() const {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Datastore::ExecQueryParams::Builder::getSql() {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Datastore::ExecQueryParams::Builder::setSql( ::zap::Text::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Datastore::ExecQueryParams::Builder::initSql(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Datastore::ExecQueryParams::Builder::adoptSql(
    ::zap::Orphan< ::zap::Text>&& value) {
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Datastore::ExecQueryParams::Builder::disownSql() {
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

inline bool Datastore::ExecQueryParams::Reader::hasFormat() const {
  return !_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline bool Datastore::ExecQueryParams::Builder::hasFormat() {
  return !_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Text::Reader Datastore::ExecQueryParams::Reader::getFormat() const {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_reader.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline  ::zap::Text::Builder Datastore::ExecQueryParams::Builder::getFormat() {
  return ::zap::_::PointerHelpers< ::zap::Text>::get(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}
inline void Datastore::ExecQueryParams::Builder::setFormat( ::zap::Text::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Text>::set(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), value);
}
inline  ::zap::Text::Builder Datastore::ExecQueryParams::Builder::initFormat(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Text>::init(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), size);
}
inline void Datastore::ExecQueryParams::Builder::adoptFormat(
    ::zap::Orphan< ::zap::Text>&& value) {
  ::zap::_::PointerHelpers< ::zap::Text>::adopt(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Text> Datastore::ExecQueryParams::Builder::disownFormat() {
  return ::zap::_::PointerHelpers< ::zap::Text>::disown(_builder.getPointerField(
      ::zap::bounded<1>() * ::zap::POINTERS));
}

inline bool Datastore::ExecQueryResults::Reader::hasResult() const {
  return !_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline bool Datastore::ExecQueryResults::Builder::hasResult() {
  return !_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS).isNull();
}
inline  ::zap::Data::Reader Datastore::ExecQueryResults::Reader::getResult() const {
  return ::zap::_::PointerHelpers< ::zap::Data>::get(_reader.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline  ::zap::Data::Builder Datastore::ExecQueryResults::Builder::getResult() {
  return ::zap::_::PointerHelpers< ::zap::Data>::get(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}
inline void Datastore::ExecQueryResults::Builder::setResult( ::zap::Data::Reader value) {
  ::zap::_::PointerHelpers< ::zap::Data>::set(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), value);
}
inline  ::zap::Data::Builder Datastore::ExecQueryResults::Builder::initResult(unsigned int size) {
  return ::zap::_::PointerHelpers< ::zap::Data>::init(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), size);
}
inline void Datastore::ExecQueryResults::Builder::adoptResult(
    ::zap::Orphan< ::zap::Data>&& value) {
  ::zap::_::PointerHelpers< ::zap::Data>::adopt(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS), kj::mv(value));
}
inline ::zap::Orphan< ::zap::Data> Datastore::ExecQueryResults::Builder::disownResult() {
  return ::zap::_::PointerHelpers< ::zap::Data>::disown(_builder.getPointerField(
      ::zap::bounded<0>() * ::zap::POINTERS));
}

}  // namespace
}  // namespace

ZAP_END_HEADER

