import shlex
import sys

from ci.defs.defs import BASE_BRANCH
from praktika.info import Info
from praktika.result import Result
from praktika.utils import Shell

# The self-extracting master binary from the CH_ARM_BINARY artifact. Required
# artifacts are downloaded into the input dir under their basename, so it lands
# at ci/tmp/clickhouse (not the producer's build tree), as a plain file that
# must be made executable before use -- the same convention other consumers
# follow (e.g. ci/jobs/install_check.py). The generator resolves the path to an
# absolute one, so a repo-relative value is fine even though it runs the binary
# from a scratch directory.
BINARY = "ci/tmp/clickhouse"
GENERATOR = "ci/jobs/scripts/docs/autogenerate/autogenerate_docs.py"

# A stable branch, force-pushed each run, so the bot keeps a single open PR that
# always carries exactly one commit off the latest master.
BRANCH = "robot/docs-autogen"
# The label the docs check exempts from the autogenerated-region edit guard
# (see ci/jobs/docs_job_mintlify.py). It also skips the changelog requirement.
# The label is provisioned once in the repository as part of the rollout (it
# already exists); the workflow only attaches it, so it stays the single source
# of truth for the label's color and description.
LABEL = "pr-autogenerated-docs"
TITLE = "Regenerate reference documentation from source"

BODY = """\
This pull request is opened automatically by the nightly documentation
autogeneration workflow. It regenerates the reference documentation artifacts
under `docs/reference/` from the documentation embedded in the ClickHouse source
(`system.documentation`).

Only the content between the `{/*AUTOGENERATED_START*/}` and
`{/*AUTOGENERATED_END*/}` markers changes. Do not edit these files by hand --
edit the documentation in the defining source code instead; the next nightly run
regenerates the artifacts.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes into CHANGELOG.md):

### Documentation entry for user-facing changes
- [ ] Documentation is written (mandatory for new features)
"""


def regenerate():
    """Regenerate the docs tree in place from the master binary.

    The artifact downloader materializes a plain file, so make it executable
    before invoking the generator."""
    return Shell.check(
        f"chmod +x {BINARY} && python3 {GENERATOR} --write --binary {BINARY} --docs-dir docs",
        verbose=True,
    )


def _open_bot_pr():
    """Return the number of the open bot pull request for BRANCH in the base
    repository, or "" if none.

    `gh pr list --head` matches by bare branch name, so a fork PR opened from a
    branch also named BRANCH would show up too. Filter to non-cross-repository
    PRs so we only ever act on the bot's own PR in the base repo, never someone
    else's fork PR."""
    return Shell.get_output(
        f"gh pr list --head {BRANCH} --state open --json number,isCrossRepository"
        " --jq 'map(select(.isCrossRepository == false)) | .[0].number // empty'"
    ).strip()


def _push_branch():
    """Force-push HEAD to BRANCH authenticated as the GitHub App.

    `actions/checkout` persists the workflow `GITHUB_TOKEN` in
    `http.https://github.com/.extraheader`, and pushes authenticated that way do
    not re-trigger workflows -- so the pull request's `synchronize` CI would never
    run on refreshed docs. Push with the App token from `enable_gh_auth` instead
    (read from the gh session and kept out of the logs via `verbose=False`), and
    clear the inherited extraheader so the tokenized URL is what authenticates.
    Mirrors the workflow-YAML push in `ci/praktika/native_jobs.py`.

    The token expands at runtime, so its literal `${token}` is kept out of the
    f-string and the URL is assembled by concatenation."""
    repo_url = (
        "https://x-access-token:${token}@github.com/"
        + shlex.quote(Info().repo_name)
        + ".git"
    )
    push_cmd = (
        'token="$(gh auth token)" && '
        "git -c http.https://github.com/.extraheader= push -f "
        + repo_url
        + f" HEAD:refs/heads/{BRANCH}"
    )
    return Shell.check(push_cmd, verbose=False)


def open_or_refresh_pr():
    """Commit the regenerated docs and open (or refresh) the bot's pull request.

    When regeneration produced no changes the docs are already in sync with the
    source, so any pull request the bot opened earlier is now stale (someone may
    have merged the same regeneration, or a later source change made the tree
    match master again). Rather than leave it advertising outdated changes, the
    stale pull request is closed and its branch deleted."""
    if not Shell.get_output("git status --porcelain docs/").strip():
        print("Docs already in sync with the source; no changes to publish.")
        pr = _open_bot_pr()
        if not pr:
            return True
        print(f"Closing stale bot pull request #{pr} and deleting branch {BRANCH}.")
        return Shell.check(
            f"gh pr close {pr} --delete-branch --comment "
            + shlex.quote(
                "The generated documentation is back in sync with the source; "
                "closing this stale autogenerated pull request."
            ),
            verbose=True,
        )

    commit = [
        "git config user.name 'robot-clickhouse'",
        "git config user.email 'robot-clickhouse@users.noreply.github.com'",
        f"git checkout -B {BRANCH}",
        "git add -A docs/",
        f"git commit -m {shlex.quote(TITLE)}",
    ]
    if not Shell.check(" && ".join(commit), verbose=True):
        return False

    if not _push_branch():
        return False

    pr = _open_bot_pr()
    if not pr:
        # First run: no bot PR yet -- create it with the label.
        return Shell.check(
            f"gh pr create --base master --head {BRANCH} "
            f"--title {shlex.quote(TITLE)} --body {shlex.quote(BODY)} --label {LABEL}",
            verbose=True,
        )
    # Existing PR: the force-push above already refreshed it. Ensure the label is
    # present, addressing the PR by number so a same-named fork PR is untouched.
    return Shell.check(f"gh pr edit {pr} --add-label {LABEL}", verbose=True)


def on_base_branch():
    """Refuse to run unless the checkout is the base branch (master).

    The workflow is SCHEDULE-triggered, but GitHub also generates a
    `workflow_dispatch` trigger and reruns replay their original ref/sha. Since
    this job force-pushes the stable BRANCH and manages a pull request, it must
    not publish from a manually dispatched feature branch or a stale rerun of
    unmerged code -- only from master."""
    branch = Info().git_branch
    if branch != BASE_BRANCH:
        print(
            f"Refusing to run: this workflow force-pushes '{BRANCH}' and manages a"
            f" pull request, so it must run against '{BASE_BRANCH}', not '{branch}'"
            " (e.g. a manual workflow_dispatch or a rerun from another ref).",
            file=sys.stderr,
        )
        return False
    return True


if __name__ == "__main__":
    results = [Result.from_commands_run(name="Run against master", command=on_base_branch)]
    # Fail closed: only regenerate / touch the pull request when the guard and
    # each prior step succeeded.
    if results[-1].is_ok():
        results.append(Result.from_commands_run(name="Regenerate docs", command=regenerate))
    if results[-1].is_ok():
        results.append(
            Result.from_commands_run(
                name="Open or refresh PR", command=open_or_refresh_pr
            )
        )
    Result.create_from(results=results).complete_job()
