import shlex

from praktika.result import Result
from praktika.utils import Shell

# The self-extracting master binary downloaded from the CH_ARM_BINARY artifact.
BINARY = "ci/tmp/build/programs/self-extracting/clickhouse"
GENERATOR = "ci/jobs/scripts/docs/autogenerate/autogenerate_docs.py"

# A stable branch, force-pushed each run, so the bot keeps a single open PR that
# always carries exactly one commit off the latest master.
BRANCH = "robot/docs-autogen"
# The label the docs check exempts from the autogenerated-region edit guard
# (see ci/jobs/docs_job_mintlify.py). It also skips the changelog requirement.
LABEL = "pr-autogenerated-docs"
TITLE = "Regenerate reference documentation from source"

BODY = """\
This pull request is opened automatically by the nightly documentation
autogeneration workflow. It regenerates the reference documentation artifacts
under `docs/reference/` from the documentation embedded in the ClickHouse source
(`system.documentation`).

Only the content between the `{/*AUTOGENERATED_START*/}` and
`{/*AUTOGENERATED_END*/}` markers changes. Do not edit these files by hand --
edit the documentation in the defining source code instead; the next nightly run
regenerates the artifacts.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes into CHANGELOG.md):

### Documentation entry for user-facing changes
- [ ] Documentation is written (mandatory for new features)
"""


def regenerate():
    """Regenerate the docs tree in place from the master binary."""
    return Shell.check(
        f"python3 {GENERATOR} --write --binary {BINARY} --docs-dir docs",
        verbose=True,
    )


def open_or_refresh_pr():
    """Commit the regenerated docs and open (or refresh) the bot's pull request.

    A no-op when regeneration produced no changes -- the docs are already in sync
    with the source, so there is nothing to open."""
    if not Shell.get_output("git status --porcelain docs/").strip():
        print("Docs already in sync with the source; no pull request needed.")
        return True

    commit = [
        "git config user.name 'robot-clickhouse'",
        "git config user.email 'robot-clickhouse@users.noreply.github.com'",
        f"git checkout -B {BRANCH}",
        "git add -A docs/",
        f"git commit -m {shlex.quote(TITLE)}",
        f"git push -f origin {BRANCH}",
    ]
    if not Shell.check(" && ".join(commit), verbose=True):
        return False

    # Create the PR if none is open for this branch; otherwise the force-push
    # above already refreshed it, so just ensure it still carries the label.
    return Shell.check(
        f"gh pr create --base master --head {BRANCH} "
        f"--title {shlex.quote(TITLE)} --body {shlex.quote(BODY)} --label {LABEL} "
        f"|| gh pr edit {BRANCH} --add-label {LABEL}",
        verbose=True,
    )


if __name__ == "__main__":
    results = [Result.from_commands_run(name="Regenerate docs", command=regenerate)]
    # Fail closed: only touch the pull request when regeneration succeeded.
    if results[-1].is_ok():
        results.append(
            Result.from_commands_run(
                name="Open or refresh PR", command=open_or_refresh_pr
            )
        )
    Result.create_from(results=results).complete_job()
