include("${Datastore_SOURCE_DIR}/cmake/dbms_glob_sources.cmake")
add_headers_and_sources(datastore_functions_time_series .)
add_library(datastore_functions_time_series OBJECT ${datastore_functions_time_series_sources} ${datastore_functions_time_series_headers})
target_link_libraries(datastore_functions_time_series PRIVATE dbms)
