datastore_add_executable (compressed_buffer compressed_buffer.cpp)
target_link_libraries (compressed_buffer PRIVATE dbms datastore_common_io datastore_common_config datastore_compression)

datastore_add_executable (decompress_perf decompress_perf.cpp)
target_link_libraries(decompress_perf PRIVATE datastore_compression ch_contrib::lz4)
