-- Tags: no-parallel

EXISTS {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS DICTIONARY {DATASTORE_DATABASE_1:Identifier}.t_01048;

DROP DATABASE IF EXISTS {DATASTORE_DATABASE_1:Identifier};
EXISTS DATABASE {DATASTORE_DATABASE_1:Identifier};
CREATE DATABASE {DATASTORE_DATABASE_1:Identifier};
USE {DATASTORE_DATABASE_1:Identifier};
EXISTS DATABASE {DATASTORE_DATABASE_1:Identifier};

DROP TABLE IF EXISTS {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS DICTIONARY {DATASTORE_DATABASE_1:Identifier}.t_01048;

CREATE TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048 (x UInt8) ENGINE = Memory;
EXISTS {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS DICTIONARY {DATASTORE_DATABASE_1:Identifier}.t_01048;

DROP TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS DICTIONARY {DATASTORE_DATABASE_1:Identifier}.t_01048;

DROP DICTIONARY IF EXISTS t_01048;
CREATE TEMPORARY TABLE t_01048 (x UInt8);
EXISTS t_01048; -- Does not work for temporary tables. Maybe have to fix.
EXISTS TABLE t_01048;
EXISTS DICTIONARY t_01048;

CREATE DICTIONARY {DATASTORE_DATABASE_1:Identifier}.t_01048 (k UInt64, v String) PRIMARY KEY k LAYOUT(FLAT()) SOURCE(HTTP(URL 'http://example.test/' FORMAT 'TSV')) LIFETIME(1000);
EXISTS {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048; -- Dictionaries are tables as well. But not all tables are dictionaries.
EXISTS DICTIONARY {DATASTORE_DATABASE_1:Identifier}.t_01048;

-- But dictionary-tables cannot be dropped as usual tables.
DROP TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048; -- { serverError CANNOT_DETACH_DICTIONARY_AS_TABLE }
DROP DICTIONARY {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS DICTIONARY {DATASTORE_DATABASE_1:Identifier}.t_01048;


CREATE TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048_2 (x UInt8) ENGINE = Memory;
CREATE VIEW {DATASTORE_DATABASE_1:Identifier}.v_01048 AS SELECT * FROM t_01048_2;
EXISTS VIEW {DATASTORE_DATABASE_1:Identifier}.v_01048;
EXISTS VIEW {DATASTORE_DATABASE_1:Identifier}.t_01048_2;
EXISTS VIEW {DATASTORE_DATABASE_1:Identifier}.v_not_exist;
DROP VIEW {DATASTORE_DATABASE_1:Identifier}.v_01048;
EXISTS VIEW {DATASTORE_DATABASE_1:Identifier}.v_01048;
EXISTS VIEW {DATASTORE_DATABASE_1:Identifier}.t_01048_2;
EXISTS VIEW {DATASTORE_DATABASE_1:Identifier}.v_not_exist;
EXISTS VIEW db_not_exists.v_not_exist;
DROP TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048_2;


DROP DATABASE {DATASTORE_DATABASE_1:Identifier};
EXISTS {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS TABLE {DATASTORE_DATABASE_1:Identifier}.t_01048;
EXISTS DICTIONARY {DATASTORE_DATABASE_1:Identifier}.t_01048;
