
DROP DATABASE IF EXISTS {DATASTORE_DATABASE_1:Identifier};
CREATE DATABASE {DATASTORE_DATABASE_1:Identifier};
USE {DATASTORE_DATABASE_1:Identifier};
CREATE TABLE t (x UInt8) ENGINE = Memory;

SELECT * FROM merge('', '');

DROP DATABASE {DATASTORE_DATABASE_1:Identifier};
