
DROP DATABASE IF EXISTS {DATASTORE_DATABASE:Identifier};
DROP DATABASE IF EXISTS {DATASTORE_DATABASE_1:Identifier};
CREATE DATABASE {DATASTORE_DATABASE:Identifier} ENGINE=Replicated('/test/02072/{database}_1', '{shard}', '{replica}_1');

SET distributed_ddl_output_mode='none';
CREATE TABLE {DATASTORE_DATABASE:Identifier}.`test%_\_` (n int) engine=Log;
SHOW TABLES FROM {DATASTORE_DATABASE:Identifier};

CREATE DATABASE {DATASTORE_DATABASE_1:Identifier} ENGINE=Replicated('/test/02072/{database}', '{shard}', '{replica}_2');
DROP DATABASE {DATASTORE_DATABASE:Identifier};
SYSTEM SYNC DATABASE REPLICA {DATASTORE_DATABASE_1:Identifier};
SHOW TABLES FROM {DATASTORE_DATABASE_1:Identifier};

DROP DATABASE {DATASTORE_DATABASE_1:Identifier};
