#!/usr/bin/env bash
# Tags: no-parallel

CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CURDIR"/../shell_config.sh

DATABASE='test_02177'
SESSION_ID="$RANDOM$RANDOM$RANDOM"

${DATASTORE_CURL} -sS "${DATASTORE_URL}" -d "DROP DATABASE IF EXISTS ${DATABASE}"
${DATASTORE_CURL} -sS "${DATASTORE_URL}" -d "CREATE DATABASE ${DATABASE}"

DATASTORE_URL_PARAMS="database=${DATABASE}"
[ -v DATASTORE_LOG_COMMENT ] && DATASTORE_URL_PARAMS="${DATASTORE_URL_PARAMS}&log_comment=${DATASTORE_LOG_COMMENT}"
DATASTORE_URL="${DATASTORE_PORT_HTTP_PROTO}://${DATASTORE_HOST}:${DATASTORE_PORT_HTTP}/?${DATASTORE_URL_PARAMS}"

${DATASTORE_CURL} -sS "${DATASTORE_URL}&session_id=${SESSION_ID}" -d 'CREATE TEMPORARY TABLE t AS SELECT currentDatabase()'
${DATASTORE_CURL} -sS "${DATASTORE_URL}&session_id=${SESSION_ID}" -d 'SELECT * FROM t'

${DATASTORE_CURL} -sS "${DATASTORE_URL}" -d "DROP DATABASE ${DATABASE}"
