#!/usr/bin/env bash

CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CURDIR"/../shell_config.sh

export DATASTORE_TEST_UNIQUE_NAME="${DATASTORE_TEST_NAME}_${DATASTORE_DATABASE}"

$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv1"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv2"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv3"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv4"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv5"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv6"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv7"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv8"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv9"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv10"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv11"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_pv12"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS test_02428_v1"
$DATASTORE_CLIENT -q "DROP TABLE IF EXISTS test_02428_Catalog"
$DATASTORE_CLIENT -q "DROP TABLE IF EXISTS ${DATASTORE_TEST_UNIQUE_NAME}.pv1"
$DATASTORE_CLIENT -q "DROP TABLE IF EXISTS ${DATASTORE_TEST_UNIQUE_NAME}.Catalog"
$DATASTORE_CLIENT -q "DROP DATABASE IF EXISTS ${DATASTORE_TEST_UNIQUE_NAME}"
$DATASTORE_CLIENT -q "DROP VIEW IF EXISTS 02428_trace_view"
$DATASTORE_CLIENT -q "DROP TABLE IF EXISTS 02428_otel_traces_trace_id_ts"
$DATASTORE_CLIENT -q "DROP TABLE IF EXISTS 02428_otel_traces"

$DATASTORE_CLIENT -q "CREATE TABLE test_02428_Catalog (Name String, Price UInt64, Quantity UInt64) ENGINE = ReplicatedMergeTree('/datastore/tables/$DATASTORE_TEST_ZOOKEEPER_PREFIX/parameterized_view', 'r1') ORDER BY Name"

$DATASTORE_CLIENT -q "INSERT INTO test_02428_Catalog VALUES ('Pen', 10, 3)"
$DATASTORE_CLIENT -q "INSERT INTO test_02428_Catalog VALUES ('Book', 50, 2)"
$DATASTORE_CLIENT -q "INSERT INTO test_02428_Catalog VALUES ('Paper', 20, 1)"

$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv1 AS SELECT * FROM test_02428_Catalog WHERE Price={price:UInt64}"
$DATASTORE_CLIENT -q "SELECT Price FROM test_02428_pv1(price=20)"
$DATASTORE_CLIENT -q "SELECT Price FROM \`test_02428_pv1\`(price=20)"

$DATASTORE_CLIENT -q "SELECT Price FROM test_02428_pv1" 2>&1 |  grep -q "UNKNOWN_QUERY_PARAMETER\|UNKNOWN_IDENTIFIER" && echo 'ERROR' || echo 'OK'
$DATASTORE_CLIENT --param_p 10 -q "SELECT Price FROM test_02428_pv1(price={p:UInt64})"

$DATASTORE_CLIENT --param_l 1 -q "SELECT Price FROM test_02428_pv1(price=50) LIMIT ({l:UInt64})"
$DATASTORE_CLIENT -q "DETACH TABLE test_02428_pv1"
$DATASTORE_CLIENT -q "ATTACH TABLE test_02428_pv1"

$DATASTORE_CLIENT -q "EXPLAIN SYNTAX SELECT * from test_02428_pv1(price=10)"

$DATASTORE_CLIENT -q "INSERT INTO test_02428_pv1 VALUES ('Bag', 50, 2)" 2>&1 |  grep -Fq "EMPTY_LIST_OF_COLUMNS_PASSED" && echo 'ERROR' || echo 'OK'

$DATASTORE_CLIENT -q "SELECT Price FROM pv123(price=20)" 2>&1 |  grep -Fq "UNKNOWN_FUNCTION" && echo 'ERROR' || echo 'OK'

$DATASTORE_CLIENT -q "CREATE VIEW test_02428_v1 AS SELECT * FROM test_02428_Catalog WHERE Price=10"

$DATASTORE_CLIENT -q "SELECT Price FROM test_02428_v1(price=10)" 2>&1 |  grep -Fq "UNKNOWN_FUNCTION" && echo 'ERROR' || echo 'OK'

$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv2 AS SELECT * FROM test_02428_Catalog WHERE Price={price:UInt64} AND Quantity={quantity:UInt64}"

$DATASTORE_CLIENT -q "SELECT Price FROM test_02428_pv2(price=50,quantity=2)"
$DATASTORE_CLIENT -q "SELECT Price FROM test_02428_pv2(price=50)"  2>&1 |  grep -Fq "UNKNOWN_QUERY_PARAMETER" && echo 'ERROR' || echo 'OK'

$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv3 AS SELECT * FROM test_02428_Catalog WHERE Price={price:UInt64} AND Quantity=3"
$DATASTORE_CLIENT -q "SELECT Price FROM test_02428_pv3(price=10)"

$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv4 AS SELECT * FROM test_02428_Catalog WHERE Price={price:UInt64} OR Price={price:UInt64}*2"
$DATASTORE_CLIENT -q "SELECT Price FROM test_02428_pv4(price=10) ORDER BY Price"

$DATASTORE_CLIENT -q "CREATE DATABASE ${DATASTORE_TEST_UNIQUE_NAME}"
$DATASTORE_CLIENT -q "CREATE TABLE ${DATASTORE_TEST_UNIQUE_NAME}.Catalog (Name String, Price UInt64, Quantity UInt64) ENGINE = Memory"
$DATASTORE_CLIENT -q "INSERT INTO ${DATASTORE_TEST_UNIQUE_NAME}.Catalog VALUES ('Pen', 10, 3)"
$DATASTORE_CLIENT -q "INSERT INTO ${DATASTORE_TEST_UNIQUE_NAME}.Catalog VALUES ('Book', 50, 2)"
$DATASTORE_CLIENT -q "INSERT INTO ${DATASTORE_TEST_UNIQUE_NAME}.Catalog VALUES ('Paper', 20, 1)"
$DATASTORE_CLIENT -q "CREATE VIEW ${DATASTORE_TEST_UNIQUE_NAME}.pv1 AS SELECT * FROM ${DATASTORE_TEST_UNIQUE_NAME}.Catalog WHERE Price={price:UInt64}"
$DATASTORE_CLIENT -q "SELECT Price FROM ${DATASTORE_TEST_UNIQUE_NAME}.pv1(price=20)"
$DATASTORE_CLIENT -q "SELECT Price FROM \`${DATASTORE_TEST_UNIQUE_NAME}.pv1\`(price=20) SETTINGS enable_analyzer = 0"  2>&1 |  grep -Fq "UNKNOWN_FUNCTION" &&  echo 'ERROR' || echo 'OK'
$DATASTORE_CLIENT -q "SELECT Price FROM \`${DATASTORE_TEST_UNIQUE_NAME}.pv1\`(price=20) SETTINGS enable_analyzer = 1"


$DATASTORE_CLIENT -q "INSERT INTO test_02428_Catalog VALUES ('Book2', 30, 8)"
$DATASTORE_CLIENT -q "INSERT INTO test_02428_Catalog VALUES ('Book3', 30, 8)"
$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv5 AS SELECT Price FROM test_02428_Catalog WHERE Price={price:UInt64} HAVING Quantity in (SELECT {quantity:UInt64}) LIMIT {limit:UInt64}"
$DATASTORE_CLIENT -q "SELECT Price FROM test_02428_pv5(price=30, quantity=8, limit=1)"
$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv6 AS SELECT Price+{price:UInt64} FROM test_02428_Catalog GROUP BY Price+{price:UInt64} ORDER BY Price+{price:UInt64}"
$DATASTORE_CLIENT -q "SELECT * FROM test_02428_pv6(price=10)"
$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv7 AS SELECT Price/{price:UInt64} FROM test_02428_Catalog ORDER BY Price"
$DATASTORE_CLIENT -q "SELECT * FROM test_02428_pv7(price=10)"

$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv8 AS SELECT Price FROM test_02428_Catalog WHERE Price IN ({prices:Array(UInt64)}) ORDER BY Price"
$DATASTORE_CLIENT -q "SELECT * FROM test_02428_pv8(prices=[10,20])"

$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv9 AS SELECT Price FROM test_02428_Catalog WHERE Price IN (10,20) AND Quantity={quantity:UInt64} ORDER BY Price"
$DATASTORE_CLIENT -q "SELECT * FROM test_02428_pv9(quantity=3)"

$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv10 AS SELECT Price FROM test_02428_Catalog WHERE Price={Pri:UInt64} ORDER BY Price"
$DATASTORE_CLIENT -q "SELECT * FROM test_02428_pv10(Pri=10)"

$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv11 AS SELECT * from ( SELECT Price FROM test_02428_Catalog WHERE Price={price:UInt64} )"
$DATASTORE_CLIENT -q "SELECT * FROM test_02428_pv11(price=10)"

$DATASTORE_CLIENT -q "CREATE VIEW test_02428_pv12 AS SELECT * from ( SELECT Price FROM test_02428_Catalog WHERE Price IN (SELECT number FROM numbers({price:UInt64})) )"
$DATASTORE_CLIENT -q "SELECT * FROM test_02428_pv12(price=11)"

$DATASTORE_CLIENT -q "CREATE TABLE 02428_otel_traces (TraceId String) ENGINE = ReplicatedMergeTree('/datastore/tables/$DATASTORE_TEST_ZOOKEEPER_PREFIX/otel_traces', 'r1') ORDER BY TraceId"
$DATASTORE_CLIENT -q "CREATE TABLE 02428_otel_traces_trace_id_ts (TraceId String, Start Timestamp) ENGINE  = ReplicatedMergeTree('/datastore/tables/$DATASTORE_TEST_ZOOKEEPER_PREFIX/otel_traces_trace_id_ts', 'r1') ORDER BY TraceId"

$DATASTORE_CLIENT -q "INSERT INTO 02428_otel_traces(TraceId) VALUES ('1')"
$DATASTORE_CLIENT -q "INSERT INTO 02428_otel_traces_trace_id_ts(TraceId, Start) VALUES('1', now())"

$DATASTORE_CLIENT -q "CREATE VIEW 02428_trace_view AS WITH  {trace_id:String} AS trace_id,
                              ( SELECT min(Start) FROM 02428_otel_traces_trace_id_ts WHERE TraceId = trace_id
                               ) AS start SELECT
                       TraceId AS traceID
                       FROM 02428_otel_traces"
$DATASTORE_CLIENT -q "SELECT * FROM 02428_trace_view(trace_id='1')"

$DATASTORE_CLIENT -q "CREATE MATERIALIZED VIEW test_02428_mv1 ENGINE = ReplicatedMergeTree('/datastore/tables/$DATASTORE_TEST_ZOOKEEPER_PREFIX/materialized_view', 'r1') ORDER BY Name AS SELECT * FROM test_02428_Catalog;"
$DATASTORE_CLIENT -q "SELECT * FROM test_02428_mv1(test)" 2>&1 |  grep -Fq "UNKNOWN_FUNCTION" && echo 'ERROR' || echo 'OK'

$DATASTORE_CLIENT -q "DROP VIEW test_02428_mv1"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_pv1"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_pv2"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_pv3"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_pv5"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_pv6"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_pv7"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_pv8"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_pv9"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_pv10"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_pv11"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_pv12"
$DATASTORE_CLIENT -q "DROP VIEW test_02428_v1"
$DATASTORE_CLIENT -q "DROP TABLE test_02428_Catalog"
$DATASTORE_CLIENT -q "DROP TABLE ${DATASTORE_TEST_UNIQUE_NAME}.pv1"
$DATASTORE_CLIENT -q "DROP TABLE ${DATASTORE_TEST_UNIQUE_NAME}.Catalog"
$DATASTORE_CLIENT -q "DROP DATABASE ${DATASTORE_TEST_UNIQUE_NAME}"
$DATASTORE_CLIENT -q "DROP VIEW 02428_trace_view"
$DATASTORE_CLIENT -q "DROP TABLE 02428_otel_traces_trace_id_ts"
$DATASTORE_CLIENT -q "DROP TABLE 02428_otel_traces"
