#!/usr/bin/env bash
CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CUR_DIR"/../shell_config.sh

DATASTORE_USER="user_$DATASTORE_DATABASE"

$DATASTORE_CLIENT "

DROP USER IF EXISTS ${DATASTORE_USER};
CREATE USER ${DATASTORE_USER};

CREATE TABLE ${DATASTORE_DATABASE}.02703_rqtable (x UInt8) ENGINE = MergeTree ORDER BY x;
INSERT INTO ${DATASTORE_DATABASE}.02703_rqtable VALUES (1), (2), (3), (4);

SELECT '-- row policies for database';
CREATE ROW POLICY ${DATASTORE_DATABASE}_db_policy ON ${DATASTORE_DATABASE}.* USING 1 AS PERMISSIVE TO ALL;
CREATE ROW POLICY ${DATASTORE_DATABASE}_tb_policy ON ${DATASTORE_DATABASE}.table USING 1 AS PERMISSIVE TO ALL;
SELECT '  -- SHOW CREATE POLICY ${DATASTORE_DATABASE} ON ${DATASTORE_DATABASE}.*';
SHOW CREATE POLICY ${DATASTORE_DATABASE}_db_policy ON ${DATASTORE_DATABASE}.*;
SELECT '  -- SHOW CREATE POLICY ON ${DATASTORE_DATABASE}.*';
SHOW CREATE POLICY ON ${DATASTORE_DATABASE}.*;
SELECT '  -- SHOW CREATE POLICY ON ${DATASTORE_DATABASE}.\`*\`';
SHOW CREATE POLICY ON ${DATASTORE_DATABASE}.\`*\`;
DROP POLICY ${DATASTORE_DATABASE}_db_policy ON ${DATASTORE_DATABASE}.*;
DROP POLICY ${DATASTORE_DATABASE}_tb_policy ON ${DATASTORE_DATABASE}.table;
"

$DATASTORE_CLIENT --query "CREATE ROW POLICY any_02703 ON *.some_table USING 1 AS PERMISSIVE TO ALL;" 2>&1 | grep -q "SYNTAX_ERROR"

$DATASTORE_CLIENT "
CREATE TABLE 02703_rqtable_default (x UInt8) ENGINE = MergeTree ORDER BY x;

CREATE ROW POLICY ${DATASTORE_DATABASE}_filter_11_db_policy ON * USING x=1 AS permissive TO ALL;
CREATE ROW POLICY ${DATASTORE_DATABASE}_filter_11_policy ON 02703_rqtable_default USING x=2 AS permissive TO ALL;

INSERT INTO 02703_rqtable_default VALUES (1), (2), (3), (4);

SELECT 'R1, R2: (x == 1) OR (x == 2)';
SELECT * FROM 02703_rqtable_default;

DROP TABLE 02703_rqtable_default;

SELECT 'Check system.query_log';
SYSTEM FLUSH LOGS query_log;
SELECT query, used_row_policies FROM system.query_log WHERE event_date >= yesterday() AND event_time >= now() - 600 AND current_database == currentDatabase() AND type == 'QueryStart' AND query_kind == 'Select' ORDER BY event_time_microseconds;

DROP ROW POLICY ${DATASTORE_DATABASE}_filter_11_db_policy ON *;
DROP ROW POLICY ${DATASTORE_DATABASE}_filter_11_policy ON 02703_rqtable_default;

USE ${DATASTORE_DATABASE};
SELECT '  -- CREATE DATABASE-LEVEL POLICY IN CURRENT DATABASE';
CREATE ROW POLICY db2_02703 ON * TO ${DATASTORE_USER};
SHOW CREATE POLICY db2_02703 ON *;

DROP ROW POLICY db2_02703 ON *;

DROP USER ${DATASTORE_USER};
"
