DROP DATABASE IF EXISTS {DATASTORE_DATABASE_1:Identifier};

CREATE DATABASE {DATASTORE_DATABASE_1:Identifier};

CREATE TABLE {DATASTORE_DATABASE_1:Identifier}.t (x UInt8) ENGINE = MergeTree() ORDER BY x;

INSERT INTO {DATASTORE_DATABASE_1:Identifier}.t SELECT number FROM numbers(10);

SELECT t.x FROM {DATASTORE_DATABASE_1:Identifier}.t ORDER BY t.x;

DROP DATABASE IF EXISTS {DATASTORE_DATABASE_1:Identifier};
