DROP DATABASE IF EXISTS {DATASTORE_DATABASE:Identifier};
CREATE DATABASE IF NOT EXISTS {DATASTORE_DATABASE:Identifier};

CREATE TABLE IF NOT EXISTS {DATASTORE_DATABASE:Identifier}.r1 (name String) Engine=Memory();
SHOW TABLES FROM {DATASTORE_DATABASE:Identifier};

RENAME TABLE {DATASTORE_DATABASE:Identifier}.r1 TO {DATASTORE_DATABASE:Identifier}.r1_bak;
SHOW TABLES FROM {DATASTORE_DATABASE:Identifier};

RENAME {DATASTORE_DATABASE:Identifier}.r1_bak TO {DATASTORE_DATABASE:Identifier}.r1;
SHOW TABLES FROM {DATASTORE_DATABASE:Identifier};

CREATE TABLE IF NOT EXISTS {DATASTORE_DATABASE:Identifier}.r2 (name String) Engine=Memory();
RENAME {DATASTORE_DATABASE:Identifier}.r1 TO {DATASTORE_DATABASE:Identifier}.r1_bak,
       {DATASTORE_DATABASE:Identifier}.r2 TO {DATASTORE_DATABASE:Identifier}.r2_bak;
SHOW TABLES FROM {DATASTORE_DATABASE:Identifier};

CREATE TABLE IF NOT EXISTS {DATASTORE_DATABASE:Identifier}.source_table (
                id UInt64,
                value String
            ) ENGINE = Memory;

CREATE DICTIONARY IF NOT EXISTS {DATASTORE_DATABASE:Identifier}.test_dictionary
(
    id UInt64,
    value String
)
PRIMARY KEY id
SOURCE(DATASTORE(TABLE '{DATASTORE_DATABASE:String}.dictionary_table'))
LAYOUT(FLAT())
LIFETIME(MIN 0 MAX 1000);

SHOW DICTIONARIES FROM {DATASTORE_DATABASE:Identifier};

RENAME {DATASTORE_DATABASE:Identifier}.test_dictionary TO {DATASTORE_DATABASE:Identifier}.test_dictionary_2;
SHOW DICTIONARIES FROM {DATASTORE_DATABASE:Identifier};

SHOW DATABASES LIKE '{DATASTORE_DATABASE:String}';
RENAME {DATASTORE_DATABASE:Identifier} TO {DATASTORE_DATABASE_1:Identifier}; -- { serverError UNKNOWN_TABLE }
SHOW DATABASES LIKE '{DATASTORE_DATABASE:String}';

DROP DATABASE IF EXISTS {DATASTORE_DATABASE:Identifier};
