-- https://github.com/ClickHouse/Datastore/issues/61947
SET enable_analyzer=1;

DROP DATABASE IF EXISTS {DATASTORE_DATABASE:Identifier};
DROP DATABASE IF EXISTS {DATASTORE_DATABASE_1:Identifier};

CREATE DATABASE {DATASTORE_DATABASE:Identifier};
CREATE DATABASE {DATASTORE_DATABASE_1:Identifier};
CREATE TABLE {DATASTORE_DATABASE:Identifier}.`1-1` (field Int8) ENGINE = Memory;
CREATE TABLE {DATASTORE_DATABASE_1:Identifier}.`1-1` (field Int8) ENGINE = Memory;
CREATE TABLE {DATASTORE_DATABASE_1:Identifier}.`2-1` (field Int8) ENGINE = Memory;

INSERT INTO {DATASTORE_DATABASE:Identifier}.`1-1` VALUES (1);

SELECT *
FROM {DATASTORE_DATABASE:Identifier}.`1-1`
LEFT JOIN {DATASTORE_DATABASE_1:Identifier}.`1-1` ON {DATASTORE_DATABASE:Identifier}.`1-1`.field = {DATASTORE_DATABASE_1:Identifier}.`1-1`.field;

SELECT '';

SELECT * FROM
(
SELECT 'using asterisk', {DATASTORE_DATABASE:Identifier}.`1-1`.*, {DATASTORE_DATABASE_1:Identifier}.`1-1`.*
FROM {DATASTORE_DATABASE:Identifier}.`1-1`
LEFT JOIN {DATASTORE_DATABASE_1:Identifier}.`1-1` USING field
UNION ALL
SELECT 'using field name', {DATASTORE_DATABASE:Identifier}.`1-1`.field, {DATASTORE_DATABASE_1:Identifier}.`1-1`.field
FROM {DATASTORE_DATABASE:Identifier}.`1-1`
LEFT JOIN {DATASTORE_DATABASE_1:Identifier}.`1-1` USING field
)
ORDER BY ALL;
