DROP DATABASE IF EXISTS {DATASTORE_DATABASE:Identifier};
CREATE DATABASE IF NOT EXISTS {DATASTORE_DATABASE:Identifier} ENGINE = Memory;
DROP TABLE IF EXISTS {DATASTORE_DATABASE:Identifier}.v0;
CREATE MATERIALIZED VIEW {DATASTORE_DATABASE:Identifier}.v0 REFRESH AFTER 1 SECOND APPEND ENGINE = MergeTree() ORDER BY tuple() AS (SELECT 1 c0);
DETACH TABLE {DATASTORE_DATABASE:Identifier}.v0 PERMANENTLY; -- { serverError NOT_IMPLEMENTED }
ALTER TABLE {DATASTORE_DATABASE:Identifier}.v0 MODIFY REFRESH AFTER 1 SECOND APPEND;
DROP TABLE IF EXISTS {DATASTORE_DATABASE:Identifier}.v0;
DROP DATABASE IF EXISTS {DATASTORE_DATABASE:Identifier};
